material_libraries = ["camera_suzanne.materials.toml"]

[render]
reference = "presets/relax_256spp_16bounce.render.toml"

[camera]
reference = "camera_suzanne.camera.toml"

[tonemap]
reference = "presets/aces.tonemap.toml"

[[geometry]]
type = "instance"
mesh = "Suzanne.obj"
translate = [0.0, 0.0, 0.0]
rotate = [-0.3826834261417389, 0.0, 0.0, 0.9238795638084412]
scale = [1.0, 0.9999998807907104, 0.9999998807907104]
