# Cornell Box — Empty
# Walls and area light only.
# 
# Syntax reference: see SceneLoader.hpp

material_libraries = ["cornell.materials.toml"]

[render]
reference = "presets/preview.render.toml"

[camera]
reference = "presets/cornell.camera.toml"
translate = [0.0, 2.73, -8.0]
rotate_x = 0.0000
rotate_y = 180.0000

[[geometry]]
type = "instance"
mesh = "cornell.obj"
materials = { Floor = "WhiteWall", Ceiling = "WhiteWall", AreaLight = "AreaLight", BackWall = "WhiteWall", LeftWall = "RedWall", RightWall = "GreenWall" }
rotate_y = 180.0000  # compensates for the 180deg Y bake in cornell.obj
