material_libraries = ["fixture_transparency_plane.materials.toml"]

[render]
reference = "presets/comparison_ibl_512spp.render.toml"

[camera]
reference = "presets/fixture_ibl.camera.toml"

[tonemap]
tonemapper = "agx"

[[geometry]]
type = "sphere"
radius = 0.5
material = "MatteRed"
translate = [0.0, 0.6, 0.4]
